name: markdown_editor
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - PyQt5==5.15.7
    - PyQtWebEngine==5.15.6
    - markdown2==2.4.3
    - pyperclip==1.8.2
    - pyinstaller==6.1.0
